# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: helloworld.proto

require 'google/protobuf'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("helloworld.proto", :syntax => :proto3) do
    add_message "helloworld.Request" do
      optional :message, :string, 1
    end
    add_message "helloworld.Response" do
      optional :message, :string, 1
    end
    add_message "helloworld.SendTaskR" do
      optional :message, :string, 1
    end
    add_message "helloworld.Empty" do
    end
  end
end

module Helloworld
  Request = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("helloworld.Request").msgclass
  Response = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("helloworld.Response").msgclass
  SendTaskR = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("helloworld.SendTaskR").msgclass
  Empty = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("helloworld.Empty").msgclass
end
