
version: "3.0"
services:
  broker:
    image: eclipse-mosquitto
    ports:
      - 1883:1883
    volumes:
      - ./mosquitto.conf:/mosquitto/config/mosquitto.conf
    deploy:
      replicas: 1
      placement:
        constraints: [node.role == manager]
  pub:
    image: localhost:5000/publisher
    build: ./publisher
    environment:
      - TOPIC=general
      - BROKERNAME=research.upb.edu
      - PORT=11182
    deploy:
      replicas: 5
      placement:
        constraints: [node.role == manager]
    depends_on:
      - broker
  sub:
    image: localhost:5000/subscriber
    build: ./subscriber
    environment:
      - TOPIC=general
      - HOST=research.upb.edu
      - PORT=11182
    deploy:
      replicas: 5
      placement:
        constraints: [node.role == worker]
